#define BDK_HELPER_FIRST_MBUFF_SKIP 184
#define BDK_HELPER_NOT_FIRST_MBUFF_SKIP 0
#define BDK_HELPER_ENABLE_IPD 1
#define  BDK_HELPER_INPUT_TAG_TYPE BDK_SSO_TAG_TYPE_ORDERED
#define BDK_HELPER_INPUT_PORT_SKIP_MODE	BDK_PIP_PORT_CFG_MODE_SKIPL2

#define BDK_PKO_MAX_PORTS_INTERFACE0 4
#define BDK_PKO_QUEUES_PER_PORT_INTERFACE0 2
#define BDK_PKO_MAX_PORTS_INTERFACE1 4
#define BDK_PKO_QUEUES_PER_PORT_INTERFACE1 2
#define BDK_PKO_QUEUES_PER_PORT_PCI 2
#define BDK_PKO_QUEUES_PER_PORT_LOOP 2
    /* We use two queues per port for SRIO1. Having two queues per
        port with two ports gives us four queues, one for each mailbox */
#define BDK_PKO_QUEUES_PER_PORT_SRIO0 2
#define BDK_PKO_QUEUES_PER_PORT_SRIO1 2

#define BDK_ENABLE_SSO_CHECKS 1

