/**
 * @file
 *
 * Functions for controlling the system configuration.
 *
 * <hr>$Revision: 49448 $<hr>
 *
 * @addtogroup hal
 * @{
 */

typedef enum
{
    BDK_CONFIG_FPA_POOL_SIZE0,
    BDK_CONFIG_FPA_POOL_SIZE1,
    BDK_CONFIG_FPA_POOL_SIZE2,
    BDK_CONFIG_FPA_POOL_SIZE3,
    BDK_CONFIG_FPA_POOL_SIZE4,
    BDK_CONFIG_FPA_POOL_SIZE5,
    BDK_CONFIG_FPA_POOL_SIZE6,
    BDK_CONFIG_FPA_POOL_SIZE7,

    BDK_CONFIG_FIRST_MBUFF_SKIP,
    BDK_CONFIG_NOT_FIRST_MBUFF_SKIP,
    BDK_CONFIG_ENABLE_IPD,
    BDK_CONFIG_INPUT_TAG_TYPE,
    BDK_CONFIG_INPUT_PORT_SKIP_MODE,

    BDK_CONFIG_PHY_MGMT_PORT0,
    BDK_CONFIG_PHY_MGMT_PORT1,

    BDK_CONFIG_PHY_IF0_PORT0,
    BDK_CONFIG_PHY_IF0_PORT1,
    BDK_CONFIG_PHY_IF0_PORT2,
    BDK_CONFIG_PHY_IF0_PORT3,
    BDK_CONFIG_PHY_IF1_PORT0,
    BDK_CONFIG_PHY_IF1_PORT1,
    BDK_CONFIG_PHY_IF1_PORT2,
    BDK_CONFIG_PHY_IF1_PORT3,

    BDK_CONFIG_THREAD_STACK_SIZE,
    BDK_CONFIG_MAC_ADDRESS,

    BDK_CONFIG_ILK0_LANES,
    BDK_CONFIG_ILK1_LANES,
    BDK_CONFIG_ILK0_PORTS,
    BDK_CONFIG_ILK1_PORTS,

    __BDK_CONFIG_END
} bdk_config_t;

extern uint64_t bdk_config_get(bdk_config_t cfg);
extern void bdk_config_set(bdk_config_t cfg, uint64_t value);

/** @} */
