/**
 * @file
 *
 * Functions for controlling the system configuration.
 *
 * <hr>$Revision: 49448 $<hr>
 *
 * @addtogroup hal
 * @{
 */

typedef enum
{
    BDK_CONFIG_FPA_POOL_SIZE0,
    BDK_CONFIG_FPA_POOL_SIZE1,
    BDK_CONFIG_FPA_POOL_SIZE2,
    BDK_CONFIG_FPA_POOL_SIZE3,
    BDK_CONFIG_FPA_POOL_SIZE4,
    BDK_CONFIG_FPA_POOL_SIZE5,
    BDK_CONFIG_FPA_POOL_SIZE6,
    BDK_CONFIG_FPA_POOL_SIZE7,

    BDK_CONFIG_INPUT_TAG_TYPE,
    BDK_CONFIG_INPUT_PORT_SKIP_MODE,

    BDK_CONFIG_PHY_MGMT_PORT0,
    BDK_CONFIG_PHY_MGMT_PORT1,

    BDK_CONFIG_PHY_IF0_PORT0,
    BDK_CONFIG_PHY_IF0_PORT1,
    BDK_CONFIG_PHY_IF0_PORT2,
    BDK_CONFIG_PHY_IF0_PORT3,
    BDK_CONFIG_PHY_IF1_PORT0,
    BDK_CONFIG_PHY_IF1_PORT1,
    BDK_CONFIG_PHY_IF1_PORT2,
    BDK_CONFIG_PHY_IF1_PORT3,
    BDK_CONFIG_PHY_IF2_PORT0,
    BDK_CONFIG_PHY_IF2_PORT1,
    BDK_CONFIG_PHY_IF2_PORT2,
    BDK_CONFIG_PHY_IF2_PORT3,
    BDK_CONFIG_PHY_IF3_PORT0,
    BDK_CONFIG_PHY_IF3_PORT1,
    BDK_CONFIG_PHY_IF3_PORT2,
    BDK_CONFIG_PHY_IF3_PORT3,
    BDK_CONFIG_PHY_IF4_PORT0,
    BDK_CONFIG_PHY_IF4_PORT1,
    BDK_CONFIG_PHY_IF4_PORT2,
    BDK_CONFIG_PHY_IF4_PORT3,

    BDK_CONFIG_THREAD_STACK_SIZE,
    BDK_CONFIG_MAC_ADDRESS,

    BDK_CONFIG_ILK0_LANES,
    BDK_CONFIG_ILK1_LANES,
    BDK_CONFIG_ILK0_PORTS,
    BDK_CONFIG_ILK1_PORTS,

    BDK_CONFIG_HIGIG_MODE_IF0,
    BDK_CONFIG_HIGIG_MODE_IF1,
    BDK_CONFIG_HIGIG_MODE_IF2,
    BDK_CONFIG_HIGIG_MODE_IF3,
    BDK_CONFIG_HIGIG_MODE_IF4,

    BDK_CONFIG_NUM_PACKET_BUFFERS,
    BDK_CONFIG_SHOW_LINK_STATUS,

    BDK_CONFIG_COREMASK,

    __BDK_CONFIG_END
} bdk_config_t;

extern void __bdk_config_init(void);
extern uint64_t bdk_config_get(bdk_config_t cfg);
extern void bdk_config_set(bdk_config_t cfg, uint64_t value);
extern const char *bdk_config_get_name(bdk_config_t cfg);

/** @} */
