-- Configure the BDK for a ebb7800 board.
print("Configuring for the EBB7800")

local set_config = octeon.c.bdk_config_set

-- BGX0 (QLM0 or QLM2)
set_config(octeon.CONFIG_PHY_IF0_PORT0, 0)
set_config(octeon.CONFIG_PHY_IF0_PORT1, 1)
set_config(octeon.CONFIG_PHY_IF0_PORT2, 2)
set_config(octeon.CONFIG_PHY_IF0_PORT3, 3)
-- BGX1 (QLM1 or QLM3)
set_config(octeon.CONFIG_PHY_IF1_PORT0, 4)
set_config(octeon.CONFIG_PHY_IF1_PORT1, 5)
set_config(octeon.CONFIG_PHY_IF1_PORT2, 6)
set_config(octeon.CONFIG_PHY_IF1_PORT3, 7)
-- BGX2 (QLM4)
set_config(octeon.CONFIG_PHY_IF2_PORT0, 16)
set_config(octeon.CONFIG_PHY_IF2_PORT1, 17)
set_config(octeon.CONFIG_PHY_IF2_PORT2, 18)
set_config(octeon.CONFIG_PHY_IF2_PORT3, 19)
-- BGX3 (QLM5)
set_config(octeon.CONFIG_PHY_IF3_PORT0, 20)
set_config(octeon.CONFIG_PHY_IF3_PORT1, 21)
set_config(octeon.CONFIG_PHY_IF3_PORT2, 22)
set_config(octeon.CONFIG_PHY_IF3_PORT3, 23)
-- BGX4 (QLM6)
set_config(octeon.CONFIG_PHY_IF4_PORT0, 24)
set_config(octeon.CONFIG_PHY_IF4_PORT1, 25)
set_config(octeon.CONFIG_PHY_IF4_PORT2, 26)
set_config(octeon.CONFIG_PHY_IF4_PORT3, 27)
-- BGX5 (QLM7)
set_config(octeon.CONFIG_PHY_IF5_PORT0, 28)
set_config(octeon.CONFIG_PHY_IF5_PORT1, 29)
set_config(octeon.CONFIG_PHY_IF5_PORT2, 30)
set_config(octeon.CONFIG_PHY_IF5_PORT3, 31)

-- printf("Configuring QLMs for a sample setup\n");
-- local node = octeon.MASTER_NODE
-- octeon.c.bdk_qlm_set_mode(node, 0, octeon.QLM_MODE_SGMII, 1250, 0)
-- octeon.c.bdk_qlm_set_mode(node, 1, octeon.QLM_MODE_XAUI_1X4, 3125, 0)
-- octeon.c.bdk_qlm_set_mode(node, 2, octeon.QLM_MODE_PCIE_1X8, 8000, octeon.QLM_MODE_FLAG_GEN3)
-- octeon.c.bdk_qlm_set_mode(node, 3, octeon.QLM_MODE_PCIE_1X8, 8000, octeon.QLM_MODE_FLAG_GEN3)
-- octeon.c.bdk_qlm_set_mode(node, 4, octeon.QLM_MODE_RXAUI_2X2, 6250, 0)
-- octeon.c.bdk_qlm_set_mode(node, 5, octeon.QLM_MODE_10GR_4X1, 10321, 0)
-- octeon.c.bdk_qlm_set_mode(node, 6, octeon.QLM_MODE_40GR4_1X4, 10321, 0)
-- octeon.c.bdk_qlm_set_mode(node, 7, octeon.QLM_MODE_ILK, 5000, 0)

