#!/bin/bash

rm -rf html
mkdir -p html
rm -rf cisco
mkdir -p cisco

#
# WARNING: The order of these chips in this list is hard coded into
# cvmx-csr-db-support.c. Be sure the order here and the select
# case statements there match!
#

./csr-tool.py --html \
	--csr cn78xx,octcsr_cn78xxp1 \
	--csr cn70xx,octcsr_cn70xxp1

mv bdk-csrs.h ../libbdk-arch/
mv bdk-csrs.c ../libbdk-arch/
mv csr_db.lua ../lua-modules/

