#!/bin/bash

rm -rdf html
mkdir -p html
rm -rdf cisco
mkdir -p cisco

#
# WARNING: The order of these chips in this list is hard coded into
# cvmx-csr-db-support.c. Be sure the order here and the select
# case statements there match!
#

./csr-tool.py --html \
	--csr cn56xxp1,octcsr_cn56xxp1.txt \
	--csr cn56xx,octcsr_cn56xxp2.txt \
	--csr cn52xxp1,octcsr_cn52xxp1.txt \
	--csr cn52xx,octcsr_cn52xxp2.txt \
	--csr cn63xxp1,octcsr_cn63xxp1.txt \
	--csr cn63xx,octcsr_cn63xxp2.txt \
	--csr cn68xx,octcsr_cn68xxp1.txt

mv bdk-csrs.h ../libbdk-arch/
#mv cvmx-csr-db.c ../libbdk-hal/
#mv cvmx-error-init-*.c ../libbdk-hal/

