import tools

def test(child):
    child.sendline("net")
    child.expect("TCP/IP Networking Menu")
    tools.send_menu(child, "static")
    child.expect("Interface name: ")
    child.sendline("loop00")
    child.expect("IP: ")
    child.sendline("14.0.0.2")
    child.expect("Netmask: ")
    child.sendline("255.255.255.0")
    child.expect("Gateway: ")
    child.sendline("14.0.0.1")
    # Use number so we cover that case at least once
    tools.send_menu(child, "1")
    child.expect("Interface Configuration")
    child.expect("--------- -------------")
    child.expect("LOOP00")
    child.expect("IP:14.0.0.2 Netmask:255.255.255.0 Gateway:14.0.0.1")
    child.expect("LOOP01")
    child.expect("LOOP02")
    child.expect("LOOP03")
    tools.send_menu(child, "auto")
    child.expect("Interface name: ")
    child.sendline("loop00")
    tools.send_menu(child, "dhcp")
    child.expect("Interface name: ")
    child.sendline("foo")
    tools.send_menu(child, "quit")

