import tools

def test(child):
    child.sendline("flash")
    child.expect("Flash Menu")
    tools.send_menu(child, "init")
    child.expect("NOR Flash 0:Base address:  0x800100000fc00000")
    child.expect("Vendor:        0x0001")
    child.expect("16 bit:        yes")
    child.expect("Size:          4194304 bytes")
    child.expect("Num regions:   1")
    child.expect("Erase timeout: 4505600000 cycles")
    child.expect("Write timeout: 281600 cycles")
    child.expect("Region 0: offset 0x0, 32 blocks, 131072 bytes/block")
    tools.send_menu(child, "view(CS0)")
    child.expect("Starting offset: ")
    child.sendline("0")
    child.expect("Bytes to display: ")
    child.sendline("64")
    child.expect("00000000: ")
    child.expect("00000010: ")
    child.expect("00000020: ")
    child.expect("00000030: ")
    tools.send_menu(child, "write(CS0)")
    child.expect("Enter source filename: ")
    child.sendline("foo")
    child.expect("Flash offset: ")
    child.sendline("0")
    child.expect("foo: No such file or directory")
    tools.send_menu(child, "quit")

tools.add_test(test, "Flash")
