import tools

def test(child):
    child.sendline("smi")
    child.expect("SMI/MDIO Menu")
    tools.send_menu(child, "bus0")
    child.expect("SMI/MDIO Menu - Bus 0")
    tools.send_menu(child, "scan")
    child.expect("SMI0: Scanning bus...")
    child.expect("SMI0: Address  30 \(0x1e\) responded with 0x0100")
    child.expect("SMI0: Address  31 \(0x1f\) responded with 0x0100")
    tools.send_menu(child, "read")
    child.expect("Device address \(0 - 63\): ")
    child.sendline("30")
    child.expect("Device register: ")
    child.sendline("0")
    child.expect("SMI0: Address  30 \(0x1e\) reg 0 \(0x0\) responded with 0x0100")
    tools.send_menu(child, "write")
    child.expect("Device address \(0 - 63\): ")
    child.sendline("30")
    child.expect("Device register: ")
    child.sendline("")
    child.expect("User interrupted input")
    tools.send_menu(child, "quit")
    tools.send_menu(child, "quit")

tools.add_test(test, "SMI")
