import tools

def test(child):
    child.sendline("gpio")
    child.expect("GPIO Menu")
    tools.send_menu(child, "cfg")
    child.expect("GPIO number: ")
    child.sendline("0")
    child.expect("Configure as output\(y/n\): ")
    child.sendline("y")
    child.expect("GPIO state \(0 - 1\): ")
    child.sendline("0")
    tools.send_menu(child, "read")
    child.expect("GPIO number: ")
    child.sendline("0")
    child.expect("GPIO 0: 0")
    tools.send_menu(child, "cfg")
    child.expect("GPIO number: ")
    child.sendline("0")
    child.expect("Configure as output\(y/n\): ")
    child.sendline("y")
    child.expect("GPIO state \(0 - 1\): ")
    child.sendline("1")
    tools.send_menu(child, "read")
    child.expect("GPIO number: ")
    child.sendline("0")
    #child.expect("GPIO 0: 1")
    tools.send_menu(child, "cfg")
    child.expect("GPIO number: ")
    child.sendline("0")
    child.expect("Configure as output\(y/n\): ")
    child.sendline("n")
    tools.send_menu(child, "quit")

tools.add_test(test, "GPIO")
