import tools

def test(child):
    child.sendline("twsi")
    child.expect("TWSI Menu")
    tools.send_menu(child, "bus0")
    child.expect("TWSI Menu - Bus 0")
    tools.send_menu(child, "init")
    tools.send_menu(child, "scan")
    child.expect("TWSI0: Scanning bus...")
    child.expect("TWSI0: Address  24 \(0x18\) responded")
    child.expect("TWSI0: Address  48 \(0x30\) responded")
    child.expect("TWSI0: Address  74 \(0x4a\) responded")
    child.expect("TWSI0: Address  79 \(0x4f\) responded")
    child.expect("TWSI0: Address  80 \(0x50\) responded")
    child.expect("TWSI0: Address  83 \(0x53\) responded")
    tools.send_menu(child, "read")
    child.expect("Device address \(0 - 127\): ")
    child.sendline("24")
    child.expect("Internal address width \(0 - 2\): ")
    child.sendline("0")
    child.expect("Number of bytes to read \(1 - 4\): ")
    child.sendline("1")
    child.expect("Result: 0 \(0x0\)")
    tools.send_menu(child, "write")
    child.expect("Device address \(0 - 127\): ")
    child.sendline("0")
    child.expect("Internal address width \(0 - 2\): ")
    child.sendline("1")
    child.expect("Internal address: ")
    child.sendline("0")
    child.expect("Number of bytes to write \(1 - 4\): ")
    child.sendline("1")
    child.expect("Data to write: ")
    child.sendline("")
    child.expect("User interrupted input")
    tools.send_menu(child, "quit")
    tools.send_menu(child, "quit")

tools.add_test(test, "TWSI")
