import tools

def test_main(child):
    child.sendline("srio")
    child.expect("SRIO Menu")
    tools.send_menu(child, "debug")
    child.expect("Toggle extra debug output. Currently ON")
    child.sendline("debug")
    child.expect("Toggle extra debug output. Currently OFF")
    child.sendline("debug_maint")
    child.expect("Toggle logging of maintenance. Currently ON")
    child.sendline("debug_maint")
    child.expect("Toggle logging of maintenance. Currently OFF")
    child.sendline("quit")

tools.add_test(test_main, "SRIO main menu")

def test_port(child, port):
    child.sendline("port%d" % port)
    child.expect("SRIO Menu - Port %d" % port)
    tools.send_menu(child, "init")
    child.expect("Port in")
    child.expect("mode")
    child.expect("Mhz")
    child.expect("lanes")
    tools.send_menu(child, "scan")
    tools.send_menu(child, "enum")
    tools.send_menu(child, "show")
    child.expect("SRIO port %d:" % port)
    child.expect("Device 0x%x \(8bit\) 0x%x \(16bit\)" % (port, port))
    child.expect("ID 0x0090008c")
    child.expect("Device 0x%x \(8bit\) 0x%x \(16bit\)" % (port+1, port+1))
    child.expect("ID 0x0090008c")
    tools.send_menu(child, "mread")
    child.expect("Device ID \(-1 - 65535\): ")
    child.sendline("1")
    child.expect("Do a 16 bit access\(y/n\): ")
    child.sendline("y")
    child.expect("Hop count \(0 - 255\): ")
    child.sendline("0")
    child.expect("Register address \(min 0\): ")
    child.sendline("0")
    child.expect("0x90008c")
    tools.send_menu(child, "read")
    child.expect("Device ID \(0 - 65535\): ")
    child.sendline("%d" % (port+1))
    child.expect("SRIO bus address \(min 0\): ")
    child.sendline("0")
    child.expect("Number of bytes to read \(1 - 65536\): ")
    child.sendline("8")
    child.expect("Data: 0090008c0000000a")
    child.sendline("quit")

def test_doorbell(child):
    child.sendline("port1")
    child.expect("SRIO Menu - Port 1")
    child.sendline("sdb")
    child.expect("Device ID \(0 - 65535\): ")
    child.sendline("2")
    child.expect("Do a 16 bit access\(y/n\): ")
    child.sendline("y")
    child.expect("Priority \(0 - 3\): ")
    child.sendline("2")
    child.expect("Doorbell Value \(0 - 65535\): ")
    child.sendline("0x1234")
    child.sendline("quit")
    child.sendline("port0")
    child.expect("SRIO Menu - Port 0")
    child.sendline("rdb")
    child.expect("Received doorbell:")
    child.expect("Source ID:      1")
    child.expect("Destination ID: Primary")
    child.expect("Data:           0x1234")
    child.expect("Priority:       2")
    child.expect("Type:           16 bit")
    child.expect("Sequence #:")
    child.sendline("rdb")
    child.expect("No doorbells received")
    child.sendline("quit")

def test(child):
    child.sendline("srio")
    child.expect("SRIO Menu")
    test_port(child, 0)
    test_port(child, 1)
    test_doorbell(child)
    tools.send_menu(child, "quit")

tools.add_test(test, "SRIO")

