
.PHONY: all
all:
	${MAKE} -C boot
	${MAKE} -C diagnostics
	${MAKE} -C init
	${MAKE} -C setup
	${MAKE} -C cortina

.PHONY: clean
clean:
	${MAKE} -C boot clean
	${MAKE} -C diagnostics clean
	${MAKE} -C init clean
	${MAKE} -C setup clean
	${MAKE} -C cortina clean

